spring:
  application:
    name: llm-train-inference

server:
  port: 20038
  tomcat:
    threads:
      max: 20
      min-spare: 2

logging:
  level:
    root: info
  file:
    name: ./logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10240MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      clean-history-on-start: false
      total-size-cap: 0B
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(%-25.-25method{24}:%4.4line){green} %clr(:){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    file: '%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} %-25.-25method{24}:%4.4line : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

model-path:
  qwen:
    aarch64-base-dir: /mnt/hpfs
    other-base-dir: /data
    aarch64-dataset-dir: /mnt/hpfs/train_files/datasets
    other-dataset-dir: /dataset/data
    model-input-dir: /cyc_qwen2_workspace/qwen2_folder_modified/codes/LLaMA-Factory
    model-output-dir: /cyc_qwen2_workspace/saves/output_dir
    intent-sync-dir: /data/nfs/lora_intent
