spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 1
      pool-name: meta_HikariCP
    password: Llm_app@2025
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.101.111:5432/llm
    username: llm_app

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml
